if [ -f /etc/bash.bashrc ]; then
  . /etc/bash.bashrc
fi

[ -z "$PS1" ] && return

if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;33m\]\w\[\033[00m\]\$ '

shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=50000
HISTFILESIZE=50000
HISTIGNORE="&:ls:ll:pwd:exit:clear"

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi